title: Digital Square IPS Kit
description: Documentation
theme: just-the-docs

url: https://digitalsqr.github.io/fhir-ips-kit

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
plugins:
  - jekyll-default-layout
  - jekyll-spaceship  

color_scheme: wider

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/dsqr-logo.png"

callouts:
  warning:
    title: Warning
    color: yellow

  info:
    title: Info
    color: blue

